server:
  port: 8999
  servlet:
    jsp:
      init-parameters:
        development: true
    context-path: /bbs
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bbs
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  mvc:
    view:
      prefix: /
      suffix: .jsp
  jackson:
    date-format: yyyy-MM-dd
mybatis:
  type-aliases-package: com.zpark.entity
  mapper-locations: classpath:mapper/*Mapper.xml
logging:
  level:
    root: error
    com.zpark.dao: debug